import Zcash.Snark.Fixtures.MultiAction.Honest.Negative
import Zcash.Snark.Fixtures.MultiAction.Honest.Transcript
import Zcash.Snark.Fixtures.Shared.Hex
import Zcash.Snark.Verifier.ProofBytes

/-!
# Byte-level acceptance for the honest two-action capture

The generated fixture carries the exact proof bytes consumed by the accepting Rust verifier run.
This module parses those bytes back to the captured typed proof, derives the key digest and every
Fiat–Shamir challenge through the modeled BLAKE2b transcript, and composes both facts into
`DeployedAcceptsBytes`.
-/

namespace Zcash.Snark.Fixture2

open Zcash.Snark

/-- The accepting capture's generated proof hex decoded to bytes. -/
def capturedProofBytes : List UInt8 := (hexDecode? capturedProofHex).getD []

/-- The modeled deployed reader parses the exact honest proof and consumes every byte. This is the
single native check needed to anchor the generated byte string to the typed proof. -/
theorem capturedProofBytes_decodes :
    (readProof? shape).run capturedProofBytes = some (ps, []) := by
  native_decide

/-- Serializing the parsed honest proof recovers exactly the generated proof bytes. -/
theorem serializeProof_eq_capturedProofBytes : serializeProof ps = capturedProofBytes := by
  exact serializeProof_eq_of_readProof?_eq_some capturedProofBytes_decodes

/-- The exporter-emitted pinned key description is an exact description of the captured key
(`Describes`, `Verifier/KeyDigest.lean`). Represented fields read back to `vk`; verifier-active
fields omitted by Rust's description agree through the circuit-derived key. The reader-only
quotient-piece and point-set counts come from the captured `shape`, not from `Describes`; the exact
parse above checks them at this fixture. `Fixtures/PinnedKey.lean` separately pins the printed
keygen-only fields. -/
theorem capturedPinnedKeyDescription_describes : Describes capturedPinnedKeyDescription vk vk := by
  native_decide

/-- No derived instance commitment is the identity, which the deployed transcript refuses to
absorb. -/
theorem derivedInstanceCommitment_ne_zero :
    ∀ p (column : Fin shape.numInstanceColumns), derivedInstanceCommitment p column ≠ 0 := by
  native_decide

/-- **The accepting Rust capture reaches the byte-level predicate.** The pinned key description
describes the captured key, no instance commitment is the identity, parsing is exact, the key
digest comes from that description, challenges come from the deployed BLAKE2b transcript, and the
resulting typed proof satisfies `DeployedAccepts`. -/
theorem capture_deployedAcceptsBytes :
    DeployedAcceptsBytes shape capturedURS rfl vk vk capturedPinnedKeyDescription
      derivedInstanceCommitment capturedProofBytes := by
  refine ⟨capturedPinnedKeyDescription_describes, derivedInstanceCommitment_ne_zero, ps,
    capturedProofBytes_decodes, ?_⟩
  have harg : deriveChallengesForStatement halo2Transcript
      (keyDigest capturedPinnedKeyDescription) derivedInstanceCommitment ps = ch := by
    rw [keyDigest_eq_capturedVkTranscriptRepr]
    exact deriveChallengesForStatement_matches_blake2b
  rw [harg]
  with_reducible exact capture_deployedAccepts

/-- The same accepting capture reaches the complete Lean raw entry point: instance columns are
validated first, their commitments are derived internally, and only then are the proof bytes
parsed and checked.  This is finite evidence for deployment refinement, not a universal claim
about Rust inputs. -/
theorem capture_deployedAcceptsRawBytes :
    DeployedAcceptsRawBytes shape capturedURS rfl vk vk capturedPinnedKeyDescription
      capturedRawInstances commitLagrange capturedProofBytes := by
  let valid : ValidatedInstances vk :=
    ⟨capturedRawInstances, capturedRawInstances_have_expected_column_count,
      capturedRawInstances_columns_fit⟩
  refine ⟨valid, ?_, ?_⟩
  · simp [validateInstances?, valid, capturedRawInstances_have_expected_column_count,
      capturedRawInstances_columns_fit]
  · apply deployedAcceptsBytes_congr_instanceCommitment
      (instanceCommitment := derivedInstanceCommitment)
      (instanceCommitment' := valid.commitments commitLagrange)
      (h := capture_deployedAcceptsBytes)
    · intro p column
      exact (capturedRawInstances_commitments_eq p column).symm
    · intro p column rotation hmem
      exact (capturedRawInstances_commitments_eq_on_layout p column rotation hmem).symm

end Zcash.Snark.Fixture2
