import Zcash.Circuits.Integration.ActionCopyWitness
import Zcash.Common.RelationWitness
import Zcash.Circuits.Integration.PermutationColumns

/-!
# Action permutation-cycle construction

This module identifies the common-permutation polynomials routed from the
accepted verifier relation with the σ columns generated by Action keygen. It
then constructs the exact `ResolverPermutationCycle` consumed by the generic
copy semantics, retaining only the shared augmented-commitment relation branch.

All large objects remain in their compiler-native index types. The sole domain
size equality is discharged by the generic size-transport theorem in
`PermutationColumns`.
-/

namespace Zcash.Snark

open Zcash.Arithmetic (derivedUrsGLagrange omegaOf)

open Halo2 CompPoly.CPolynomial
open Keygen
open ActionPermutationDomain
open Zcash.Circuits.Action (actionCircuit)

set_option maxHeartbeats 20000

variable {G : Type} [AddCommGroup G] [Module Fp G]
  [Inhabited G]

theorem actionCopyList_decoded :
    Halo2.Layout.V1.copyList
        (Keygen.permColsOf actionCircuit.constraintSystem)
        (Halo2.FloorPlanner.V1.starts
          (actionCircuit.operations))
        (actionCircuit.operations)
        (Keygen.constantCopyEntries actionCircuit.constraintSystem
          (actionCircuit.operations)) =
      Zcash.Snark.actionCopies.map fun pair =>
        (pair.1.pair.1, pair.1.pair.2,
          pair.2.pair.1, pair.2.pair.2) := by
  have hdecode :=
    (Zcash.Snark.decodeCopies_map
      Zcash.Snark.actionNumPermCols
      Zcash.Snark.actionDomainSize
      Zcash.Snark.actionCopyRaw
      Zcash.Snark.actionCopyBounds).symm
  simpa only [Zcash.Snark.actionCopyRaw,
    Zcash.Snark.actionPermCols, Zcash.Snark.actionConsts,
    TopLevelCircuit.regionStarts] using hdecode

omit [Module Fp G] in
theorem actionPermutationRows_eq_chunkRowName
    (pp : ProofParams) (urs : URS G)
    (poly : CommitmentId → CPoly)
    (proofIndex : Fin (actionShape pp).numProofs)
    (chunk : Fin (actionShape pp).numPermutationSets)
    (column : Fin
      (ResolverPermutationPairs
        (actionVk pp urs) poly proofIndex chunk).length)
    (row : Fin Zcash.Snark.actionDomainSize) :
    (Zcash.Snark.topLevelPermutationRows
      actionCircuit
      ((Zcash.Snark.actionChunkFlatten pp urs poly proofIndex
        ⟨chunk, row, column⟩).2 : ℕ)).getD (row : ℕ) 0 =
      chunkRowName
        (actionVk pp urs).omega
        (actionVk pp urs).delta
        (actionVk pp urs).chunkLen
        ((Zcash.Snark.actionFullSigma pp urs poly proofIndex
          ⟨chunk, row, column⟩).1 : ℕ)
        ((Zcash.Snark.actionFullSigma pp urs poly proofIndex
          ⟨chunk, row, column⟩).2.1 : ℕ)
        ((Zcash.Snark.actionFullSigma pp urs poly proofIndex
          ⟨chunk, row, column⟩).2.2 : ℕ) := by
  apply Zcash.Snark.Layout.Asm.permPolysOf_getD_eq_chunkRowName
    actionCircuit.constraintSystem
    (actionCircuit.operations)
    Zcash.Snark.actionCopies
    actionCopyList_decoded
    (actionVk pp urs).chunkLen
    (Zcash.Snark.actionChunkFlatten pp urs poly proofIndex)
  · intro rc
    let hcl : 0 < (actionVk pp urs).chunkLen := by
      rw [Zcash.Snark.actionChunkLen_eq]
      decide
    let hcover :
        Zcash.Snark.actionNumPermCols ≤
          (actionShape pp).numPermutationSets *
            (actionVk pp urs).chunkLen := by
      rw [Zcash.Snark.actionNumPermCols_eq,
        Zcash.Snark.actionNumPermutationSets_eq,
        Zcash.Snark.actionChunkLen_eq]
      decide
    let hw := Zcash.Snark.actionResolverChunkWidth
      pp urs poly proofIndex
    exact congrArg Fin.val
      (Zcash.Snark.Layout.Asm.chunkFlatten_symm_apply_row
        hcl hcover hw rc)
  · intro rc
    let hcl : 0 < (actionVk pp urs).chunkLen := by
      rw [Zcash.Snark.actionChunkLen_eq]
      decide
    let hcover :
        Zcash.Snark.actionNumPermCols ≤
          (actionShape pp).numPermutationSets *
            (actionVk pp urs).chunkLen := by
      rw [Zcash.Snark.actionNumPermCols_eq,
        Zcash.Snark.actionNumPermutationSets_eq,
        Zcash.Snark.actionChunkLen_eq]
      decide
    let hw := Zcash.Snark.actionResolverChunkWidth
      pp urs poly proofIndex
    exact Zcash.Snark.Layout.Asm.chunkFlatten_symm_apply_column
      hcl hcover hw rc

theorem zipIdx_getD_snd
    {α : Type} (xs : List α) (fallback : α)
    (index : ℕ) (hindex : index < xs.length) :
    (xs.zipIdx.getD index (fallback, 0)).2 = index := by
  rw [List.getD_eq_getElem _ _ (by simpa using hindex)]
  simp

set_option maxRecDepth 100000 in
omit [Module Fp G] in
theorem actionChunkCommonIndex
    (pp : ProofParams) (urs : URS G)
    (poly : CommitmentId → CPoly)
    (proofIndex : Fin (actionShape pp).numProofs)
    (chunk : Fin (actionShape pp).numPermutationSets)
    (column : Fin
      (ResolverPermutationPairs
        (actionVk pp urs) poly proofIndex chunk).length)
    (row : Fin Zcash.Snark.actionDomainSize) :
    (((actionVk pp urs).permutationChunks.getD chunk []).getD
        column ((.advice 0), 0)).2 =
      ((Zcash.Snark.actionChunkFlatten pp urs poly proofIndex
        ⟨chunk, row, column⟩).2 : ℕ) := by
  let vk := actionVk pp urs
  let flatten := Zcash.Snark.actionChunkFlatten pp urs poly proofIndex
  let global : ℕ := (flatten ⟨chunk, row, column⟩).2
  have hchunk : (chunk : ℕ) < 3 := by
    simpa only [Zcash.Snark.actionNumPermutationSets_eq] using chunk.isLt
  have hcolumn :
      (column : ℕ) <
        (vk.permutationChunks.getD chunk []).length := by
    simpa only [ResolverPermutationPairs,
      permutationChunkPairsOfResolver, List.length_map] using column.isLt
  have hprefix :
      (vk.permutationChunks.take chunk).flatten.length =
        (chunk : ℕ) * vk.chunkLen := by
    rw [permutationChunks_eq, Zcash.Snark.actionChunkLen_eq]
    have hcases :
        (chunk : ℕ) = 0 ∨ (chunk : ℕ) = 1 ∨
          (chunk : ℕ) = 2 := by
      omega
    rcases hcases with hzero | hone | htwo
    · simp only [hzero, List.take_zero, List.flatten_nil,
        List.length_nil, Nat.zero_mul]
    · norm_num [hone]
    · norm_num [htwo]
  have hglobal :
      global <
        actionCircuit.constraintSystem.permutationColumns.length := by
    have h := (flatten ⟨chunk, row, column⟩).2.isLt
    simpa only [global, Zcash.Snark.actionNumPermCols,
      Zcash.Snark.actionPermCols, Keygen.permColsOf,
      List.length_map] using h
  have hglobalIndex :
      (vk.permutationChunks.take chunk).flatten.length +
          (column : ℕ) =
        global := by
    rw [hprefix]
    change
      (chunk : ℕ) * vk.chunkLen + (column : ℕ) =
        ((flatten ⟨chunk, row, column⟩).2 : ℕ)
    rfl
  have hlocal :=
    Zcash.Snark.flatten_getD_at_chunk
      ((.advice 0), 0) vk.permutationChunks
      chunk column
      (by
        rw [chunkCount]
        exact chunk.isLt)
      hcolumn
  rw [hglobalIndex] at hlocal
  have hflatten :=
    Zcash.Snark.permutationChunksOf_flatten
      actionCircuit.selectorMap
      actionCircuit.constraintSystem
  change
    vk.permutationChunks.flatten =
      (actionCircuit.constraintSystem.permutationColumns.map
        (Zcash.Snark.permutationQueryReference
          (projectCS actionCircuit.selectorMap
            actionCircuit.constraintSystem))).zipIdx at hflatten
  calc
    ((vk.permutationChunks.getD chunk []).getD
        column ((.advice 0), 0)).2 =
        (vk.permutationChunks.flatten.getD
          global ((.advice 0), 0)).2 := by
      exact congrArg Prod.snd hlocal.symm
    _ =
        (((actionCircuit.constraintSystem.permutationColumns.map
          (Zcash.Snark.permutationQueryReference
            (projectCS actionCircuit.selectorMap
              actionCircuit.constraintSystem))).zipIdx).getD
          global ((.advice 0), 0)).2 := by
      rw [hflatten]
    _ = global := zipIdx_getD_snd _ (ColumnRef.advice 0) global
      (by simpa only [List.length_map] using hglobal)

theorem actionPermutationCommitment_ofKeygen
    (pp : ProofParams) (urs : URS G)
    (hk : (actionShape pp).k = urs.k)
    (setup : LagrangePrefixSetup urs)
    (column : Fin (actionShape pp).numPermutationColumns) :
    (actionVk pp urs).permutationCommonCommitment column =
      (LagrangeCommitmentKey.ofPrefix urs
        (omegaOf urs.k)
        (derivedUrsGLagrange urs)
        setup.generator_eq).commitInstance
          (topLevelPermutationRows
            actionCircuit column) 1 := by
  rw [actionCircuit.toVerifierKey_permutationCommonCommitment]
  apply PermutationCommitmentCoherence.commitment_ofKeygen
    actionCircuit urs hk setup column
  simpa only [topLevelPermutationColumnCount,
    Keygen.ProofParams.mergeDerived, Keygen.permColsOf,
    List.length_map] using column.isLt

omit [Module Fp G] in
theorem actionRowsInjectiveAtUrs
    (pp : ProofParams) (urs : URS G)
    (hk : (actionShape pp).k = urs.k) :
    Function.Injective fun i : Fin (2 ^ urs.k) =>
      (actionVk pp urs).omega ^ (i : ℕ) := by
  intro left right heq
  let left' : Fin (actionVk pp urs).n :=
    ⟨left, by
      change (left : ℕ) <
        2 ^ actionCircuit.domainExponent
      have hdomain :
          actionCircuit.domainExponent = urs.k := hk
      rw [hdomain]
      exact left.isLt⟩
  let right' : Fin (actionVk pp urs).n :=
    ⟨right, by
      change (right : ℕ) <
        2 ^ actionCircuit.domainExponent
      have hdomain :
          actionCircuit.domainExponent = urs.k := hk
      rw [hdomain]
      exact right.isLt⟩
  have hfin := rowsInjective pp urs
    (show (actionVk pp urs).omega ^ (left' : ℕ) =
        (actionVk pp urs).omega ^ (right' : ℕ) by
      exact heq)
  have hval :
      (left' : ℕ) = (right' : ℕ) :=
    congrArg (fun value : Fin (actionVk pp urs).n => (value : ℕ)) hfin
  exact Fin.ext hval

set_option maxRecDepth 100000 in
def actionResolverPermutationCycle_or_relation
    (pp : ProofParams) (urs : URS G)
    (hk : (actionShape pp).k = urs.k)
    {instanceCommitment :
      Fin (actionShape pp).numProofs → ℕ → G}
    {ps : ProofString (actionShape pp) Fp G}
    {ch : Challenges (actionShape pp).k Fp}
    {pU pW : Fp} {a : Fin (2 ^ urs.k) → Fp}
    {batchOpenings :
      OpenedBatchOpenings urs (evalVector urs.k ch.x3)
        (x4BatchCommitments
          (instanceCommitment := instanceCommitment)
          urs hk (actionVk pp urs) ps ch)
        (x4BatchEvals
          (instanceCommitment := instanceCommitment)
          (actionVk pp urs) ps ch)
        a pU pW}
    {memberDecode : ∀ i (hi : i <
        deployedX4PairCount
          (instanceCommitment := instanceCommitment)
          (actionVk pp urs) ps ch),
      OpenedMemberDecode
        (instanceCommitment := instanceCommitment)
        urs hk (actionVk pp urs) ps ch batchOpenings i hi}
    {y : Fp} {hpoly : CPoly} {deg : ℕ}
    (relation : CanonicalMemberConstraintRelation
      urs hk (actionVk pp urs) instanceCommitment ps ch pU pW a
      batchOpenings memberDecode
        (blindingFactors_lt pp urs) y hpoly deg)
    (proofIndex : Fin (actionShape pp).numProofs) :
    {cycle : ResolverPermutationCycle
        (actionVk pp urs) relation.polynomial proofIndex actionActiveRows //
      cycle.sigma =
        actionActiveSigma pp urs relation.polynomial proofIndex}
      ⊕' NontrivialRelation (F := Fp) urs.g urs.u urs.w := by
  classical
  have hkUrs : urs.k ≤ 32 := by
    have hdomain :
        actionCircuit.domainExponent = urs.k := hk
    rw [← hdomain]
    exact Nat.le_of_lt_succ domainExponent_lt
  let setup := LagrangePrefixSetup.ofDerived urs hkUrs
  -- The successful cycle is returned as data; only its sigma equality is proof-valued.
  refine bindOrRelationWitness
    (finForallOrRelationWitness fun chunk =>
      finForallOrRelationWitness fun column => ?_)
    (fun hcolumns =>
      ⟨cycleOfKeygenColumnsAt pp urs relation.polynomial proofIndex
        actionActiveRows_le_domainSize
        (Zcash.Snark.actionFullSigma
          pp urs relation.polynomial proofIndex)
        (Zcash.Snark.actionActiveSigma
          pp urs relation.polynomial proofIndex)
        hcolumns
        (Zcash.Snark.actionActiveSigma_widen
          pp urs relation.polynomial proofIndex),
        rfl⟩)
  let vk := actionVk pp urs
  let entry :=
    (vk.permutationChunks.getD chunk []).getD
      column ((.advice 0), 0)
  have hcommonIndex :=
    actionChunkCommonIndex pp urs relation.polynomial proofIndex
      chunk column ⟨0, Zcash.Snark.actionDomainSize_pos⟩
  have hcommon :
      entry.2 < (actionShape pp).numPermutationColumns := by
    rw [hcommonIndex]
    have hlt :=
      ((Zcash.Snark.actionChunkFlatten
        pp urs relation.polynomial proofIndex
        ⟨chunk, ⟨0, Zcash.Snark.actionDomainSize_pos⟩, column⟩).2).isLt
    simpa only [Zcash.Snark.actionNumPermCols,
      Zcash.Snark.actionPermCols, Keygen.permColsOf,
      Keygen.ProofParams.mergeDerived, List.length_map] using hlt
  let common : Fin (actionShape pp).numPermutationColumns :=
    ⟨entry.2, hcommon⟩
  have homega :
      vk.omega = omegaOf urs.k := by
    change
      omegaOf actionCircuit.domainExponent =
        omegaOf urs.k
    exact congrArg omegaOf hk
  let key : LagrangeCommitmentKey urs vk.omega := by
    let sourceKey :=
      LagrangeCommitmentKey.ofPrefix urs
        (omegaOf urs.k) (derivedUrsGLagrange urs)
        setup.generator_eq
    exact
      { generators := sourceKey.generators
        generator_eq := by
          intro i
          rw [homega]
          exact sourceKey.generator_eq i }
  have hcommit :
      vk.permutationCommonCommitment common =
        key.commitInstance
          (topLevelPermutationRows
            actionCircuit common) 1 := by
    have source :=
      actionPermutationCommitment_ofKeygen pp urs hk setup common
    simpa only [vk, key, LagrangeCommitmentKey.commitInstance,
      LagrangeCommitmentKey.commitRows] using source
  have hj :
      (column : ℕ) <
        (vk.permutationChunks.getD chunk []).length := by
    simpa only [vk, ResolverPermutationPairs,
      permutationChunkPairsOfResolver, List.length_map] using
        column.isLt
  have hval :
      ∀ i : Fin Zcash.Snark.actionDomainSize,
        (topLevelPermutationRows
          actionCircuit common).getD (i : ℕ) 0 =
          chunkRowName vk.omega vk.delta vk.chunkLen
            (Zcash.Snark.actionFullSigma
              pp urs relation.polynomial proofIndex
              ⟨chunk, i, column⟩).1
            (Zcash.Snark.actionFullSigma
              pp urs relation.polynomial proofIndex
              ⟨chunk, i, column⟩).2.1
            (Zcash.Snark.actionFullSigma
              pp urs relation.polynomial proofIndex
              ⟨chunk, i, column⟩).2.2 := by
    intro i
    have source :=
      actionPermutationRows_eq_chunkRowName
        pp urs relation.polynomial proofIndex chunk column i
    have hcommonRow :
        (common : ℕ) =
          ((Zcash.Snark.actionChunkFlatten
            pp urs relation.polynomial proofIndex
            ⟨chunk, i, column⟩).2 : ℕ) := by
      change entry.2 = _
      exact actionChunkCommonIndex
        pp urs relation.polynomial proofIndex chunk column i
    rw [hcommonRow]
    simpa only [vk] using source
  have hidx :
      ((vk.permutationChunks.getD chunk [])[column]).2 =
        (common : ℕ) := by
    change
      ((vk.permutationChunks.getD chunk [])[column]).2 =
        ((vk.permutationChunks.getD chunk []).getD
          column ((.advice 0), 0)).2
    rw [List.getD_eq_getElem _ _ hj]
    rfl
  have hidentified :=
    relation.resolverPermutationPairs_snd_eq_keygenSigmaColumn_or_relation_of_size
      proofIndex chunk column hj common hidx key
      (topLevelPermutationRows
        actionCircuit common)
      hcommit (actionRowsInjectiveAtUrs pp urs hk)
      (by
        unfold Zcash.Snark.actionDomainSize
        exact congrArg (2 ^ ·) hk)
      (Zcash.Snark.actionFullSigma
        pp urs relation.polynomial proofIndex)
      chunk column hval
  exact hidentified

end Zcash.Snark
