import Zcash.Circuits.Integration.ActionCopyWitness
import Zcash.Common.RelationWitness
import Zcash.Circuits.Integration.PermutationColumns

/-!
# Action permutation-cycle construction

This module identifies the common-permutation polynomials routed from the
accepted verifier relation with the σ columns generated by Action keygen. It
then constructs the exact `ResolverPermutationCycle` consumed by the generic
copy semantics, retaining only the shared augmented-commitment relation branch.

All large objects remain in their compiler-native index types. The sole domain
size equality is discharged by the generic size-transport theorem in
`PermutationColumns`.
-/

namespace Zcash.Snark

open Zcash.Arithmetic (derivedUrsGLagrange omegaOf)

open Halo2 CompPoly.CPolynomial
open Keygen
open ActionPermutationDomain
open ActionConstraintBounds (domainExponent_lt)
open Zcash.Circuits.Action (actionCircuit)

variable {G : Type} [AddCommGroup G] [Module Fp G]
  [DecidableEq G] [Inhabited G]

theorem actionCopyList_decoded :
    Halo2.Layout.V1.copyList
        (Keygen.permColsOf actionCircuit.constraintSystem)
        (Halo2.FloorPlanner.V1.starts
          (actionCircuit.operations))
        (actionCircuit.operations)
        (Keygen.constantCopyEntries actionCircuit.constraintSystem
          (actionCircuit.operations)) =
      Zcash.Snark.actionCopies.map fun pair =>
        (pair.1.pair.1, pair.1.pair.2,
          pair.2.pair.1, pair.2.pair.2) := by
  have hdecode :=
    (Zcash.Snark.decodeCopies_map
      Zcash.Snark.actionNumPermCols
      Zcash.Snark.actionDomainSize
      Zcash.Snark.actionCopyRaw
      Zcash.Snark.actionCopyBounds).symm
  simpa only [Zcash.Snark.actionCopyRaw,
    Zcash.Snark.actionPermCols, Zcash.Snark.actionConsts,
    TopLevelCircuit.regionStarts] using hdecode

omit [Module Fp G] [DecidableEq G] in
theorem actionPermutationRows_eq_chunkRowName
    (pp : ProofParams) (urs : URS G)
    (poly : CommitmentId → CPoly)
    (proofIndex : Fin pp.numProofs)
    (chunk : Fin actionCircuit.shape.numPermutationSets)
    (column : Fin
      (ResolverPermutationPairs
        (actionCircuit.toVerifierKey urs) poly proofIndex chunk).length)
    (row : Fin Zcash.Snark.actionDomainSize) :
    (Zcash.Snark.topLevelPermutationRows
      actionCircuit
      ((Zcash.Snark.actionChunkFlatten pp urs poly proofIndex
        ⟨chunk, row, column⟩).2 : ℕ)).getD (row : ℕ) 0 =
      chunkRowName
        actionCircuit.omega
        Zcash.Arithmetic.deltaFp
        actionCircuit.chunkLen
        ((Zcash.Snark.actionFullSigma pp urs poly proofIndex
          ⟨chunk, row, column⟩).1 : ℕ)
        ((Zcash.Snark.actionFullSigma pp urs poly proofIndex
          ⟨chunk, row, column⟩).2.1 : ℕ)
        ((Zcash.Snark.actionFullSigma pp urs poly proofIndex
          ⟨chunk, row, column⟩).2.2 : ℕ) := by
  apply Zcash.Snark.Layout.Asm.permPolysOf_getD_eq_chunkRowName
    actionCircuit.constraintSystem
    (actionCircuit.operations)
    Zcash.Snark.actionCopies
    actionCopyList_decoded
    actionCircuit.chunkLen
    (Zcash.Snark.actionChunkFlatten pp urs poly proofIndex)
  · intro rc
    exact congrArg Fin.val
      (Zcash.Snark.actionChunkFlatten_symm_apply_row
        pp urs poly proofIndex rc)
  · intro rc
    exact Zcash.Snark.actionChunkFlatten_symm_apply_column
      pp urs poly proofIndex rc

theorem zipIdx_getD_snd
    {α : Type} (xs : List α) (fallback : α)
    (index : ℕ) (hindex : index < xs.length) :
    (xs.zipIdx.getD index (fallback, 0)).2 = index := by
  rw [List.getD_eq_getElem _ _ (by simpa using hindex)]
  simp

set_option maxRecDepth 100000 in
omit [Module Fp G] [DecidableEq G] in
theorem actionChunkCommonIndex
    (pp : ProofParams) (urs : URS G)
    (poly : CommitmentId → CPoly)
    (proofIndex : Fin pp.numProofs)
    (chunk : Fin actionCircuit.shape.numPermutationSets)
    (column : Fin
      (ResolverPermutationPairs
        (actionCircuit.toVerifierKey urs) poly proofIndex chunk).length) :
    ((actionCircuit.verifierCS.permutationChunks.getD chunk []).getD
        column ((.advice 0), 0)).2 =
      (chunk : ℕ) * actionCircuit.chunkLen + (column : ℕ) := by
  let vk := actionCircuit.toVerifierKey urs
  let global : ℕ :=
    (chunk : ℕ) * actionCircuit.chunkLen + (column : ℕ)
  have hchunk :
      (chunk : ℕ) < vk.permutationChunks.length := by
    rw [actionCircuit.toVerifierKey_permutationChunks_length]
    exact chunk.isLt
  have hcolumn :
      (column : ℕ) <
        (vk.permutationChunks.getD chunk []).length := by
    simpa only [ResolverPermutationPairs,
      permutationChunkPairsOfResolver, List.length_map] using column.isLt
  have hprefix :
      (vk.permutationChunks.take chunk).flatten.length =
        (chunk : ℕ) * vk.chunkLen := by
    exact actionCircuit.toVerifierKey_permutationChunks_take_flatten_length
      urs chunk hchunk
  have hglobal :
      global <
        actionCircuit.permutationColumnCount := by
    have h :=
      ((Zcash.Snark.actionChunkFlatten pp urs poly proofIndex
        ⟨chunk, ⟨0, Zcash.Snark.actionDomainSize_pos⟩, column⟩).2).isLt
    simpa only [global,
      Zcash.Snark.actionChunkFlatten_apply_column,
      Zcash.Snark.actionNumPermCols_eq_derived] using h
  have hglobalIndex :
      (vk.permutationChunks.take chunk).flatten.length +
          (column : ℕ) =
        global := by
    rw [hprefix]
    simp only [vk, global,
      actionCircuit.toVerifierKey_chunkLen]
  have hlocal :=
    Zcash.Snark.flatten_getD_at_chunk
      ((.advice 0), 0) vk.permutationChunks
      chunk column
      hchunk
      hcolumn
  rw [hglobalIndex] at hlocal
  have hflatten :
      vk.permutationChunks.flatten =
      (actionCircuit.permutationColumns.map
          (Zcash.Snark.permutationQueryReference
            actionCircuit.adviceQueryLayout
            actionCircuit.fixedQueryLayout
            actionCircuit.instanceQueryLayout)).zipIdx := by
    rw [TopLevelCircuit.toVerifierKey_permutationChunks]
    exact Zcash.Snark.verifierCS_permutationChunks_flatten actionCircuit
  calc
    ((vk.permutationChunks.getD chunk []).getD
        column ((.advice 0), 0)).2 =
        (vk.permutationChunks.flatten.getD
          global ((.advice 0), 0)).2 := by
      exact congrArg Prod.snd hlocal.symm
    _ =
        (((actionCircuit.permutationColumns.map
          (Zcash.Snark.permutationQueryReference
            actionCircuit.adviceQueryLayout
            actionCircuit.fixedQueryLayout
            actionCircuit.instanceQueryLayout)).zipIdx).getD
          global ((.advice 0), 0)).2 := by
      rw [hflatten]
    _ = global := zipIdx_getD_snd _ (ColumnRef.advice 0) global
      (by
        simpa only [List.length_map,
          TopLevelCircuit.permutationColumnCount] using hglobal)

omit [Module Fp G] [DecidableEq G] in
theorem actionRowsInjectiveAtUrs
    (urs : URS G)
    (hk : actionCircuit.domainExponent = urs.k) :
    Function.Injective fun i : Fin (2 ^ urs.k) =>
      (actionCircuit.toVerifierKey urs).omega ^ (i : ℕ) := by
  simpa only [actionCircuit.toVerifierKey_omega] using
    TopLevelAssignment.domainRowsInjective_of_domainExponent_eq
      (top := actionCircuit) domainExponent_lt hk

set_option maxRecDepth 100000 in
def actionResolverPermutationCycle_or_relation
    (pp : ProofParams) (urs : URS G)
    (hk : actionCircuit.domainExponent = urs.k)
    {instanceCommitment :
      Fin pp.numProofs → ℕ → G}
    {ps : ProofString (actionShape pp) Fp G}
    {ch : Challenges actionCircuit.domainExponent Fp}
    {pU pW : Fp} {a : Fin (2 ^ urs.k) → Fp}
    {batchOpenings :
      OpenedBatchOpenings urs (evalVector urs.k ch.x3)
        (x4BatchCommitments
          (shape := actionShape pp)
          (instanceCommitment := instanceCommitment)
          urs hk
            (actionCircuit.toVerifierKey urs) ps ch)
        (x4BatchEvals
          (shape := actionShape pp)
          (instanceCommitment := instanceCommitment)
          (actionCircuit.toVerifierKey urs) ps ch)
        a pU pW}
    {memberDecode : ∀ i (hi : i <
        deployedX4PairCount
          (shape := actionShape pp)
          (instanceCommitment := instanceCommitment)
          (actionCircuit.toVerifierKey urs) ps ch),
      OpenedMemberDecode
        (shape := actionShape pp)
        (instanceCommitment := instanceCommitment)
        urs hk
          (actionCircuit.toVerifierKey urs) ps ch batchOpenings i hi}
    {y : Fp} {hpoly : CPoly} {deg : ℕ}
    (relation : CanonicalMemberConstraintRelation
      (shape := actionShape pp)
      urs hk
        (actionCircuit.toVerifierKey urs) instanceCommitment ps ch pU pW a
      batchOpenings memberDecode
        (actionCircuit.toVerifierKey_blindingFactors_lt_n urs)
        y hpoly deg)
    (proofIndex : Fin pp.numProofs) :
    ResolverPermutationCycleWitness
        (actionCircuit.toVerifierKey urs) relation.polynomial proofIndex
        actionActiveRows
        (actionActiveSigma pp urs relation.polynomial proofIndex)
      ⊕' AugmentedRelationWitness (F := Fp) urs.g urs.u urs.w := by
  classical
  have hkUrs : urs.k ≤ 32 := by
    rw [← hk]
    exact Nat.le_of_lt_succ domainExponent_lt
  let setup := LagrangePrefixSetup.ofDerived urs hkUrs
  -- The successful cycle is returned as data; only its sigma equality is proof-valued.
  refine bindOrRelationWitness
    (finForallOrRelationWitness fun chunk =>
      finForallOrRelationWitness fun column => ?_)
    (fun hcolumns =>
      ⟨cycleOfKeygenColumnsAt pp urs relation.polynomial proofIndex
        actionActiveRows_le_domainSize
        (Zcash.Snark.actionFullSigma
          pp urs relation.polynomial proofIndex)
        (Zcash.Snark.actionActiveSigma
          pp urs relation.polynomial proofIndex)
        hcolumns
        (Zcash.Snark.actionActiveSigma_widen
          pp urs relation.polynomial proofIndex),
        rfl⟩)
  let vk := actionCircuit.toVerifierKey urs
  have hcommonIndex :=
    actionChunkCommonIndex pp urs relation.polynomial proofIndex
      chunk column
  have hcommon :
      (chunk : ℕ) * actionCircuit.chunkLen + (column : ℕ) <
        actionCircuit.permutationColumnCount := by
    have hlt :=
      ((Zcash.Snark.actionChunkFlatten
        pp urs relation.polynomial proofIndex
        ⟨chunk, ⟨0, Zcash.Snark.actionDomainSize_pos⟩, column⟩).2).isLt
    simpa only [Zcash.Snark.actionChunkFlatten_apply_column,
      Zcash.Snark.actionNumPermCols_eq_derived] using hlt
  let common : Fin actionCircuit.permutationColumnCount :=
    ⟨(chunk : ℕ) * actionCircuit.chunkLen + (column : ℕ), hcommon⟩
  have homega :
      vk.omega = omegaOf urs.k := by
    simpa only [vk, actionCircuit.toVerifierKey_omega,
      TopLevelCircuit.omega] using congrArg omegaOf hk
  let key : LagrangeCommitmentKey urs vk.omega := by
    let sourceKey :=
      LagrangeCommitmentKey.ofPrefix urs
        (omegaOf urs.k) (derivedUrsGLagrange urs)
        setup.generator_eq
    exact
      { generators := sourceKey.generators
        generator_eq := by
          intro i
          rw [homega]
          exact sourceKey.generator_eq i }
  have hcommit :
      vk.permutationCommonCommitment common =
        key.commitInstance
          (topLevelPermutationRows
            actionCircuit common) 1 := by
    simp only [vk]
    rw [actionCircuit.toVerifierKey_permutationCommonCommitment]
    have source :=
      PermutationCommitmentCoherence.commitment_ofKeygen
        actionCircuit urs hk setup common
        common.isLt
    simpa only [topLevelPermutationCommitment, key,
      LagrangeCommitmentKey.commitInstance,
      LagrangeCommitmentKey.commitRows] using source
  have hj :
      (column : ℕ) <
        (vk.permutationChunks.getD chunk []).length := by
    simpa only [vk, ResolverPermutationPairs,
      permutationChunkPairsOfResolver, List.length_map] using
        column.isLt
  have hval :
      ∀ i : Fin Zcash.Snark.actionDomainSize,
        (topLevelPermutationRows
          actionCircuit common).getD (i : ℕ) 0 =
          chunkRowName vk.omega vk.delta vk.chunkLen
            (Zcash.Snark.actionFullSigma
              pp urs relation.polynomial proofIndex
              ⟨chunk, i, column⟩).1
            (Zcash.Snark.actionFullSigma
              pp urs relation.polynomial proofIndex
              ⟨chunk, i, column⟩).2.1
            (Zcash.Snark.actionFullSigma
              pp urs relation.polynomial proofIndex
              ⟨chunk, i, column⟩).2.2 := by
    intro i
    have source :=
      actionPermutationRows_eq_chunkRowName
        pp urs relation.polynomial proofIndex chunk column i
    have hcommonRow :
        (common : ℕ) =
          ((Zcash.Snark.actionChunkFlatten
            pp urs relation.polynomial proofIndex
            ⟨chunk, i, column⟩).2 : ℕ) := by
      simp only [common,
        Zcash.Snark.actionChunkFlatten_apply_column]
    rw [hcommonRow]
    simpa only [vk,
      actionCircuit.toVerifierKey_omega,
      actionCircuit.toVerifierKey_delta,
      actionCircuit.toVerifierKey_chunkLen] using source
  have hidx :
      ((vk.permutationChunks.getD chunk [])[column]).2 =
        (common : ℕ) := by
    calc
      ((vk.permutationChunks.getD chunk [])[column]).2 =
          ((vk.permutationChunks.getD chunk []).getD
            column ((.advice 0), 0)).2 :=
        congrArg Prod.snd (List.getD_eq_getElem _ _ hj).symm
      _ = ((actionCircuit.verifierCS.permutationChunks.getD chunk []).getD
            column ((.advice 0), 0)).2 := by
        simp only [vk, actionCircuit.toVerifierKey_permutationChunks]
      _ = (chunk : ℕ) * actionCircuit.chunkLen + (column : ℕ) :=
        hcommonIndex
      _ = (common : ℕ) := (Fin.val_mk hcommon).symm
  have hidentified :=
    relation.resolverPermutationPairs_snd_eq_keygenSigmaColumn_or_relation_of_size
      proofIndex chunk column hj common hidx key
      (topLevelPermutationRows
        actionCircuit common)
      hcommit (actionRowsInjectiveAtUrs urs hk)
      (by
        simpa only [Zcash.Snark.actionDomainSize] using
          congrArg (2 ^ ·) hk)
      (Zcash.Snark.actionFullSigma
        pp urs relation.polynomial proofIndex)
      chunk column hval
  exact hidentified

end Zcash.Snark
