import Zcash.Snark.Fixtures.Shared.Hex
import Zcash.Snark.Fixtures.SingleAction.Honest.Negative
import Zcash.Snark.Fixtures.SingleAction.Honest.Transcript
import Zcash.Snark.Verifier.ProofBytes

/-!
# Byte-level acceptance for the honest single-action capture

The generated fixture carries the exact proof bytes consumed by the accepting Rust verifier run.
This module parses those bytes back to the captured typed proof, derives the key digest and every
Fiat–Shamir challenge through the modeled BLAKE2b transcript, and composes both facts into
`DeployedAcceptsBytes`.
-/

namespace Zcash.Snark.Fixture

open Zcash.Snark

/-- The accepting capture's generated proof hex decoded to bytes. -/
def capturedProofBytes : List UInt8 := (hexDecode? capturedProofHex).getD []

/-- The modeled deployed reader parses the exact honest proof and consumes every byte. This is the
single native check needed to anchor the generated byte string to the typed proof. -/
theorem capturedProofBytes_decodes :
    (readProof? shape).run capturedProofBytes = some (ps, []) := by
  native_decide

/-- Serializing the parsed honest proof recovers exactly the generated proof bytes. -/
theorem serializeProof_eq_capturedProofBytes : serializeProof ps = capturedProofBytes := by
  exact serializeProof_eq_of_readProof?_eq_some capturedProofBytes_decodes

/-- **The accepting Rust capture reaches the byte-level predicate.** Parsing is exact, the key
digest comes from the pinned key description, challenges come from the deployed BLAKE2b
transcript, and the resulting typed proof satisfies `DeployedAccepts`. -/
theorem capture_deployedAcceptsBytes :
    DeployedAcceptsBytes shape capturedURS rfl vk PinnedKey.pinnedKeyDescription
      derivedInstanceCommitment capturedProofBytes := by
  refine ⟨ps, capturedProofBytes_decodes, ?_⟩
  rw [keyDigest_eq_capturedVkTranscriptRepr,
    deriveChallengesForStatement_matches_blake2b]
  exact capture_deployedAccepts

end Zcash.Snark.Fixture
