import Zcash.Snark.Fixtures.Shared.Hex
import Zcash.Snark.Fixtures.SingleAction.Honest.Negative
import Zcash.Snark.Fixtures.SingleAction.Honest.Transcript
import Zcash.Snark.Verifier.ProofBytes

/-!
# Byte-level acceptance for the honest single-action capture

The generated fixture carries the exact proof bytes consumed by the accepting Rust verifier run.
This module parses those bytes back to the captured typed proof, derives the key digest and every
Fiat–Shamir challenge through the modeled BLAKE2b transcript, and composes both facts into
`DeployedAcceptsBytes`.
-/

namespace Zcash.Snark.Fixture

open Zcash.Snark

/-- The accepting capture's generated proof hex decoded to bytes. -/
def capturedProofBytes : List UInt8 := (hexDecode? capturedProofHex).getD []

/-- The modeled deployed reader parses the exact honest proof and consumes every byte. This is the
single native check needed to anchor the generated byte string to the typed proof. -/
theorem capturedProofBytes_decodes :
    (readProof? shape).run capturedProofBytes = some (ps, []) := by
  native_decide

/-- Serializing the parsed honest proof recovers exactly the generated proof bytes. -/
theorem serializeProof_eq_capturedProofBytes : serializeProof ps = capturedProofBytes := by
  exact serializeProof_eq_of_readProof?_eq_some capturedProofBytes_decodes

/-- The exporter-emitted pinned key description is an exact description of the captured key
(`Describes`, `Verifier/KeyDigest.lean`). Represented fields read back to `vk`; verifier-active
fields omitted by Rust's description agree between the separately designated and used keys.
Printed column counts cover every query layout, and permutation column and commitment arities
agree. The reader-only quotient-piece and point-set counts come from the captured `shape`, not
from `Describes`; the exact parse above checks them at this fixture. `Fixtures/PinnedKey.lean`
separately pins the printed keygen-only fields. -/
theorem capturedPinnedKeyDescription_describes : Describes capturedPinnedKeyDescription vk vk := by
  native_decide

private def replaceStructField (fieldName : String) (replacement : DebugValue) :
    DebugValue → DebugValue
  | .struct name fields => .struct name (fields.map fun field =>
      if field.1 == fieldName then (field.1, replacement) else field)
  | value => value

/-- A previously accepted non-Rust-emittable mutation: declare zero fixed columns and commitments
while retaining the captured fixed-query layout. -/
private def omittedFixedCoverageDescription : String :=
  let cs := replaceStructField "num_fixed_columns" (.atom "0")
    (descriptionCs capturedPinnedKeyDescription)
  let pinned := replaceStructField "cs" cs (descriptionValue capturedPinnedKeyDescription)
  DebugValue.renderCompact (replaceStructField "fixed_commitments" (.list []) pinned)

/-- Every fixed query must now fall below the printed fixed-column count, so the description
cannot leave a verifier-reachable fixed commitment unconstrained. -/
theorem capturedPinnedKeyDescription_rejects_omitted_fixed_coverage :
    ¬ Describes omittedFixedCoverageDescription vk vk := by
  native_decide

/-! These are two-key coherence checks. The description is checked against the unchanged
canonical `vk`; `VerifyingKeyAgrees` then rejects a different verifier-used key. They do not claim
that fields omitted from Rust's pinned description are reconstructed from its text. -/

theorem capturedPinnedKeyDescription_rejects_changed_used_blindingFactors :
    ¬ Describes capturedPinnedKeyDescription vk
      { vk with blindingFactors := vk.blindingFactors + 1 } := by
  intro h
  have hEq := h.blindingFactors_eq
  simp at hEq

theorem capturedPinnedKeyDescription_rejects_changed_used_delta :
    ¬ Describes capturedPinnedKeyDescription vk { vk with delta := vk.delta + 1 } := by
  intro h
  have hEq := h.delta_eq
  simp at hEq

theorem capturedPinnedKeyDescription_rejects_changed_used_chunkLen :
    ¬ Describes capturedPinnedKeyDescription vk { vk with chunkLen := vk.chunkLen + 1 } := by
  intro h
  have hEq := h.chunkLen_eq
  simp at hEq

theorem capturedPinnedKeyDescription_rejects_changed_used_permutationChunks :
    ¬ Describes capturedPinnedKeyDescription vk { vk with permutationChunks := [] } := by
  intro h
  have hEq := h.permutationChunks_eq
  have hne : vk.permutationChunks ≠ [] := by native_decide
  exact hne hEq

/-- No derived instance commitment is the identity, which the deployed transcript refuses to
absorb. -/
theorem derivedInstanceCommitment_ne_zero :
    ∀ p (column : Fin shape.numInstanceColumns), derivedInstanceCommitment p column ≠ 0 := by
  native_decide

/-- **The accepting Rust capture reaches the byte-level predicate.** The pinned key description
describes the captured key, no instance commitment is the identity, parsing is exact, the key
digest comes from that description, challenges come from the deployed BLAKE2b transcript, and the
resulting typed proof satisfies `DeployedAccepts`. -/
theorem capture_deployedAcceptsBytes :
    DeployedAcceptsBytes shape capturedURS rfl vk vk capturedPinnedKeyDescription
      derivedInstanceCommitment capturedProofBytes := by
  refine ⟨capturedPinnedKeyDescription_describes, derivedInstanceCommitment_ne_zero, ps,
    capturedProofBytes_decodes, ?_⟩
  have harg : deriveChallengesForStatement halo2Transcript
      (keyDigest capturedPinnedKeyDescription) derivedInstanceCommitment ps = ch := by
    rw [keyDigest_eq_capturedVkTranscriptRepr]
    exact deriveChallengesForStatement_matches_blake2b
  rw [harg]
  with_reducible exact capture_deployedAccepts

/-- The same accepting capture reaches the complete Lean raw entry point: instance columns are
validated first, their commitments are derived internally, and only then are the proof bytes
parsed and checked.  This is finite evidence for deployment refinement, not a universal claim
about Rust inputs. -/
theorem capture_deployedAcceptsRawBytes :
    DeployedAcceptsRawBytes shape capturedURS rfl vk vk capturedPinnedKeyDescription
      capturedRawInstances commitLagrange capturedProofBytes := by
  let valid : ValidatedInstances vk :=
    ⟨capturedRawInstances, capturedRawInstances_have_expected_column_count,
      capturedRawInstances_columns_fit⟩
  refine ⟨valid, ?_, ?_⟩
  · simp [validateInstances?, valid, capturedRawInstances_have_expected_column_count,
      capturedRawInstances_columns_fit]
  · apply deployedAcceptsBytes_congr_instanceCommitment
      (instanceCommitment := derivedInstanceCommitment)
      (instanceCommitment' := valid.commitments commitLagrange)
      (h := capture_deployedAcceptsBytes)
    · intro p column
      exact (capturedRawInstances_commitments_eq p column).symm
    · intro p column rotation hmem
      exact (capturedRawInstances_commitments_eq_on_layout p column rotation hmem).symm

end Zcash.Snark.Fixture
