import Zcash.Snark.Fixtures.Shared.Hex
import Zcash.Snark.Fixtures.SingleAction.Honest.Negative
import Zcash.Snark.Fixtures.SingleAction.Honest.Transcript
import Zcash.Snark.Verifier.ProofBytes

/-!
# Byte-level acceptance for the honest single-action capture

The generated fixture carries the exact proof bytes consumed by the accepting Rust verifier run.
This module parses those bytes back to the captured typed proof, derives the key digest and every
Fiat–Shamir challenge through the modeled BLAKE2b transcript, and composes both facts into
`DeployedAcceptsBytes`.
-/

namespace Zcash.Snark.Fixture

open Zcash.Snark

/-- The accepting capture's generated proof hex decoded to bytes. -/
def capturedProofBytes : List UInt8 := (hexDecode? capturedProofHex).getD []

/-- The modeled deployed reader parses the exact honest proof and consumes every byte. This is the
single native check needed to anchor the generated byte string to the typed proof. -/
theorem capturedProofBytes_decodes :
    (readProof? shape).run capturedProofBytes = some (ps, []) := by
  native_decide

/-- Serializing the parsed honest proof recovers exactly the generated proof bytes. -/
theorem serializeProof_eq_capturedProofBytes : serializeProof ps = capturedProofBytes := by
  exact serializeProof_eq_of_readProof?_eq_some capturedProofBytes_decodes

/-- The exporter-emitted pinned key description describes the captured key and shape
(`Describes`, `Verifier/KeyDigest.lean`): its fields read back to `vk`'s and `shape`'s, and the
counts `readProof?` reads by are the pinned constraint system's. `Fixtures/PinnedKey.lean` states
the same reading field by field. -/
theorem capturedPinnedKeyDescription_describes : Describes capturedPinnedKeyDescription vk := by
  native_decide

/-- No derived instance commitment is the identity, which the deployed transcript refuses to
absorb. -/
theorem derivedInstanceCommitment_ne_zero :
    ∀ p (column : Fin shape.numInstanceColumns), derivedInstanceCommitment p column ≠ 0 := by
  native_decide

/-- **The accepting Rust capture reaches the byte-level predicate.** The pinned key description
describes the captured key, no instance commitment is the identity, parsing is exact, the key
digest comes from that description, challenges come from the deployed BLAKE2b transcript, and the
resulting typed proof satisfies `DeployedAccepts`. -/
theorem capture_deployedAcceptsBytes :
    DeployedAcceptsBytes shape capturedURS rfl vk capturedPinnedKeyDescription
      derivedInstanceCommitment capturedProofBytes := by
  refine ⟨capturedPinnedKeyDescription_describes, derivedInstanceCommitment_ne_zero, ps,
    capturedProofBytes_decodes, ?_⟩
  have harg : deriveChallengesForStatement halo2Transcript
      (keyDigest capturedPinnedKeyDescription) derivedInstanceCommitment ps = ch := by
    rw [keyDigest_eq_capturedVkTranscriptRepr]
    exact deriveChallengesForStatement_matches_blake2b
  rw [harg]
  with_reducible exact capture_deployedAccepts

end Zcash.Snark.Fixture
