import Zcash.Circuits.Specs.Types
import Zcash.Circuits.Specs.Bitrange
import Zcash.Circuits.Specs.Pallas
import Zcash.Circuits.Specs.PallasCert
import Zcash.Circuits.Specs.Sinsemilla
import Zcash.Circuits.Specs.SinsemillaBreak
import Zcash.Circuits.Specs.SinsemillaGenerators
import Zcash.Circuits.Utilities.RunningSum
import Zcash.Circuits.Ecc.Defs
import Zcash.Circuits.Ecc.DoubleAndAdd
import Zcash.Circuits.Ecc.AddTheorems
import Zcash.Circuits.Ecc.AddIncompleteTheorems
import Zcash.Circuits.Ecc.MulTheorems
import Zcash.Circuits.Ecc.MulIncompleteTheorems
import Zcash.Circuits.Ecc.MulCompleteTheorems
import Zcash.Circuits.Ecc.MulOverflowTheorems
import Zcash.Circuits.Ecc.MulAssignTheorems
import Zcash.Circuits.Ecc.MulFixed.Theorems
import Zcash.Circuits.Ecc.MulFixed.BaseFieldElemTheorems
import Zcash.Circuits.Ecc.MulFixed.ShortTheorems
import Zcash.Circuits.Ecc.MulFixed.CertCheck
import Zcash.Circuits.Ecc.MulFixed.Certs.NullifierK
import Zcash.Circuits.Ecc.MulFixed.Certs.ValueCommitR
import Zcash.Circuits.Ecc.MulFixed.Certs.SpendAuthG
import Zcash.Circuits.Ecc.MulFixed.Certs.CommitIvkR
import Zcash.Circuits.Ecc.MulFixed.Certs.NoteCommitR
import Zcash.Circuits.Ecc.MulFixed.Certs.ValueCommitV
import Zcash.Circuits.Sinsemilla.HVec
import Zcash.Circuits.Sinsemilla.ChipTheorems
import Zcash.Circuits.Sinsemilla.ChainTheorems
import Zcash.Circuits.Sinsemilla.CommitDomainTheorems
import Zcash.Circuits.Poseidon.Constants
import Zcash.Circuits.Poseidon.Pow5Theorems
import Zcash.Circuits.Poseidon.SpongeTheorems
import Zcash.Circuits.Poseidon.HashTheorems
import Zcash.Circuits.NoteCommit.CanonicityTheorems
import Zcash.Circuits.NoteCommit.DecomposeTheorems
import Zcash.Circuits.NoteCommit.MainTheorems
import Zcash.Circuits.CommitIvk.GateTheorems
import Zcash.Circuits.CommitIvk.ChunkTheorems
import Zcash.Circuits.CommitIvk.MainTheorems
import Zcash.Circuits.Ecc.Basic
import Zcash.Circuits.Ecc.WitnessPoint
import Zcash.Circuits.Ecc.AddIncomplete
import Zcash.Circuits.Ecc.Add
import Zcash.Circuits.Ecc.MulIncomplete
import Zcash.Circuits.Ecc.MulComplete
import Zcash.Circuits.Ecc.MulOverflow
import Zcash.Circuits.Ecc.Mul
import Zcash.Circuits.Ecc.MulFixed
import Zcash.Circuits.Ecc.MulFixed.BaseFieldElem
import Zcash.Circuits.Ecc.MulFixed.FullWidth
import Zcash.Circuits.Ecc.MulFixed.Short
import Zcash.Circuits.Utilities.LookupRangeCheck
import Zcash.Circuits.CommitIvk.Gate
import Zcash.Circuits.CommitIvk.Bundle
import Zcash.Circuits.CommitIvk.Composite
import Zcash.Circuits.NoteCommit.Gates
import Zcash.Circuits.NoteCommit.Decompose
import Zcash.Circuits.NoteCommit.Canonicity
import Zcash.Circuits.NoteCommit.Composites
import Zcash.Circuits.NoteCommit.YComposite
import Zcash.Circuits.NoteCommit.Main
import Zcash.Circuits.NoteCommit.MainBundle
import Zcash.Circuits.CommitIvk.Main
import Zcash.Circuits.CommitIvk.MainBundle
import Zcash.Circuits.Utilities.AddChip
import Zcash.Circuits.Poseidon.Pow5
import Zcash.Circuits.Poseidon.Rounds
import Zcash.Circuits.Poseidon.Permute
import Zcash.Circuits.Poseidon.Hash
import Zcash.Circuits.Sinsemilla.Basic
import Zcash.Circuits.Sinsemilla.HashPiece
import Zcash.Circuits.Sinsemilla.Chain
import Zcash.Circuits.Action.DeriveNullifier
import Zcash.Circuits.Action.ValueCommit
import Zcash.Circuits.Action.SpendAuthority
import Zcash.Circuits.Action.AddressIntegrity
import Zcash.Circuits.Ecc.Chip
import Zcash.Circuits.Action.Circuit
import Zcash.Circuits.Action.Bundle
import Zcash.Circuits.Action.RealBases
import Zcash.Circuits.Action.Spec
import Zcash.Circuits.Action.Separation
import Zcash.Circuits.Action.Shape
import Zcash.Circuits.Action.Shape.Anchors
import Zcash.Circuits.Integration

/-!
# Orchard-protocol circuits

Aggregator for the Orchard-protocol (halo2-native) circuit modules. These are kept
separate from the main `Clean` library export and can be built with `lake build Zcash`.
-/
