#!/usr/bin/env bash
# Check the per-artifact provenance manifest of the machine-generated fingerprint captures.
#
# `scripts/regenerate-fingerprint-fixtures.sh` proves the committed captures regenerate
# byte-for-byte from the pinned Orchard commit, but only when a regeneration actually runs.
# This check binds each committed artifact to its recorded provenance on every CI run, with no
# toolchain: every manifest entry (`Zcash/Snark/Fixtures/MANIFEST.tsv` — path, sha256,
# generator, source, invocation) must name an existing file whose digest matches, and — the
# rejection direction — every generated-looking artifact must carry a manifest entry. A capture
# edited in place fails the digest; a new or renamed capture smuggled in without provenance
# fails the sweep, whatever it is named.
#
# "Generated-looking" mirrors the regeneration script's own set check: a `.lean` file under
# `Zcash/Snark/Fixtures/` whose first line is the exporter header, any `.hex` file there, and
# the vendored pinned-key description `circuit_description_post_nu6_3` (an orchard source file
# at the pinned Orchard commit, not exporter output, but bound to that commit the same way).
# Keep `EXPORTER_HEADER_RE` in sync between the two scripts. Run from the repository root;
# exits non-zero on violation.
set -euo pipefail
cd "$(dirname "$0")/.."

MANIFEST=Zcash/Snark/Fixtures/MANIFEST.tsv
EXPORTER_HEADER_RE='^-- Auto-generated by halo2 `dump_vesta_lean_fixture(_match_only)?`\. Do not edit by hand\.$'

if [[ ! -f "$MANIFEST" ]]; then
  echo "VIOLATION: $MANIFEST is missing" >&2
  exit 1
fi

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

status=0

# ── Every manifest entry: five fields, unique path, existing file, matching digest ─────────
manifest_paths=""
while IFS=$'\t' read -r path digest generator source invocation; do
  [[ -z "$path" || "$path" == \#* ]] && continue
  if [[ -z "$digest" || -z "$generator" || -z "$source" || -z "$invocation" ]]; then
    echo "VIOLATION: manifest entry for '$path' is missing a field (need path, sha256, generator, source, invocation)" >&2
    status=1
    continue
  fi
  if grep -qxF "$path" <<< "$manifest_paths"; then
    echo "VIOLATION: duplicate manifest entry for $path" >&2
    status=1
  fi
  manifest_paths+="$path"$'\n'
  if [[ ! -f "$path" ]]; then
    echo "VIOLATION: manifest entry $path does not exist" >&2
    status=1
    continue
  fi
  actual=$(sha256 "$path")
  if [[ "$actual" != "$digest" ]]; then
    echo "VIOLATION: $path digest $actual does not match its manifest entry $digest" >&2
    status=1
  fi
done < "$MANIFEST"

# ── Every generated-looking artifact must have a manifest entry, and vice versa ────────────
generated=""
while IFS= read -r f; do
  if head -n 1 "$f" | grep -qE "$EXPORTER_HEADER_RE"; then
    generated+="$f"$'\n'
  fi
done < <(find Zcash/Snark/Fixtures -name '*.lean' | sort)
while IFS= read -r f; do
  generated+="$f"$'\n'
done < <(find Zcash/Snark/Fixtures \( -name '*.hex' -o -name 'circuit_description_post_nu6_3' \) | sort)

while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  if ! grep -qxF "$f" <<< "$manifest_paths"; then
    echo "VIOLATION: generated-looking artifact $f has no manifest entry" >&2
    status=1
  fi
done <<< "$generated"

while IFS= read -r p; do
  [[ -z "$p" ]] && continue
  if ! grep -qxF "$p" <<< "$generated"; then
    echo "VIOLATION: manifest entry $p is not a generated-looking artifact (stale entry?)" >&2
    status=1
  fi
done <<< "$manifest_paths"

if [[ $status -eq 0 ]]; then
  count=$(grep -c . <<< "$manifest_paths")
  echo "fixture manifest: ${count} artifact(s), digests and provenance entries all match."
fi
exit $status
