#!/usr/bin/env bash
# Regenerate every verifier-fingerprint fixture family from pinned upstream PR snapshots, and
# diff the results against the committed artifacts.
#
# The honest families (SingleAction, MultiAction) are captures of accepting runs of the
# deployed verifier; the random match-only families come from the same pipeline plus the
# capture tooling. The base match-only pipeline is released in halo2_proofs 0.3.5 and orchard
# 0.15.5; the proof-byte exporter and deployed decoder checks are pinned to zcash/halo2#933 and
# zcash/orchard#544 below. Both commits are fetched through the canonical zcash repositories,
# and Orchard #544's temporary Cargo pin of halo2_proofs is asserted to resolve exactly the
# #933 snapshot through the canonical URL. Every cargo invocation runs --locked. CI runs this
# script (fixtures.yml), enforcing all four families byte-for-byte at those reviewed snapshots.
#
# Sources are cloned from the canonical public repository; set ORCHARD_SRC to a local checkout
# path containing the pinned commit to clone Orchard from that instead. Set REGEN_WORK_DIR to
# keep/reuse the build tree across runs (much faster); it is reset hard to the pinned
# commit each run. All four families are committed, so every generated artifact is diffed
# byte-for-byte; a generated artifact with no committed counterpart (a future
# not-yet-ingested shape) is copied to REGEN_OUT_DIR (default scripts/generated/,
# gitignored). See Zcash/Snark/Fixtures/PROVENANCE.md.
#
# Every run first asserts the committed capture-artifact set equals the pinned list below
# (so a new or renamed family cannot sit in the tree unregenerated) and that each capture
# opens with the exporter's header. `--check-set` runs only those repo-local assertions —
# no clone, no cargo — which is what CI runs on every event, outside the regeneration's
# path filter.
#
# Run from anywhere; exits non-zero on any violation.
set -euo pipefail
cd "$(dirname "$0")/.."

# Exact reviewed snapshots. The PR numbers document where the commits are reviewed; the SHAs,
# not their movable heads, are the reproducibility pins: a pin the PR head has moved past is
# fetched by SHA (`prepare_orchard`).
ORCHARD_COMMIT=b81271110ed363ba8455369a925dec21db9e452f # zcash/orchard#544
ORCHARD_PR=544
ORCHARD_URL=${ORCHARD_SRC:-https://github.com/zcash/orchard.git}
HALO2_COMMIT=fbc2dc537c97f70881021b79a686bc6477eca394 # zcash/halo2#933
HALO2_PR=933
HALO2_URL=https://github.com/zcash/halo2.git

REPO_ROOT=$PWD
OUT_DIR=${REGEN_OUT_DIR:-scripts/generated}

# generated-file : committed-path : requirement
# "required": the committed file must exist and match byte-for-byte. Every committed
# family is required — a mismatch means the committed artifact drifted from what the
# pinned snapshots regenerate, or went missing. "optional" (currently unused) is for
# generated artifacts with no committed counterpart yet — a future not-yet-ingested
# shape — which are stashed in $OUT_DIR instead of failing.
pairs=(
  "SingleAction.Honest.Fixture.lean:Zcash/Snark/Fixtures/SingleAction/Honest/Fixture.lean:required"
  "MultiAction.Honest.Fixture.lean:Zcash/Snark/Fixtures/MultiAction/Honest/Fixture.lean:required"
  "SingleAction.Random.Fixture.lean:Zcash/Snark/Fixtures/SingleAction/Random/Fixture.lean:required"
  "MultiAction.Random.Fixture.lean:Zcash/Snark/Fixtures/MultiAction/Random/Fixture.lean:required"
  "SingleAction.Random.proof-bytes.hex:Zcash/Snark/Fixtures/SingleAction/Random/proof-bytes.hex:required"
  "MultiAction.Random.proof-bytes.hex:Zcash/Snark/Fixtures/MultiAction/Random/proof-bytes.hex:required"
)

# The committed capture-artifact set must be exactly the pinned pairs list above. Without this,
# a new or renamed family would compile under `FixtureCheck` while matching no fixtures.yml
# filter path and no diff entry here — carried in the tree as a "capture" that nothing
# regenerates. Every committed capture must also open with the exporter's header, so a
# hand-authored file cannot pose as generated output. The check runs in both directions:
# canonically named artifacts (`Fixture.lean`, any `*.hex`) must equal the pinned list, and —
# because the pinned basenames are only a convention — every `.lean` under `Fixtures/` that
# carries the exporter header must be in the pinned list, whatever it is named. A capture
# smuggled in under a novel basename either carries the header (caught here) or claims to be
# hand-written Lean (a lie review can see, with no regeneration pipeline to hide behind).
EXPORTER_HEADER_RE='^-- Auto-generated by halo2 `dump_vesta_lean_fixture(_match_only)?`\. Do not edit by hand\.$'
check_artifact_set() {
  local committed expected f
  committed=$(find Zcash/Snark/Fixtures -type f \
    \( -name 'Fixture.lean' -o -name '*.hex' \) | LC_ALL=C sort)
  expected=$(printf '%s\n' "${pairs[@]}" | cut -d: -f2 | LC_ALL=C sort)
  if [[ "$committed" != "$expected" ]]; then
    echo "VIOLATION: committed capture artifacts do not match the pinned regeneration list:" >&2
    diff <(printf '%s\n' "$expected") <(printf '%s\n' "$committed") >&2 || true
    exit 1
  fi
  while IFS= read -r f; do
    [[ "$f" == *.lean ]] || continue
    if ! head -n 1 "$f" | grep -qE "$EXPORTER_HEADER_RE"; then
      echo "VIOLATION: $f lacks the generated-exporter header" >&2
      exit 1
    fi
  done <<< "$committed"
  while IFS= read -r f; do
    if head -n 1 "$f" | grep -qE "$EXPORTER_HEADER_RE"; then
      if ! grep -qxF "$f" <<< "$expected"; then
        echo "VIOLATION: $f carries the exporter header but is not in the pinned regeneration list" >&2
        exit 1
      fi
    fi
  done < <(find Zcash/Snark/Fixtures -type f -name '*.lean' | LC_ALL=C sort)
  echo "capture-artifact set matches the pinned regeneration list, with exporter headers."
}

# `--check-set` runs the repo-local assertions alone — no clone, no cargo — so CI can run them
# on every event, outside the expensive regeneration's path filter.
if [[ "${1:-}" == "--check-set" ]]; then
  check_artifact_set
  exit 0
fi

check_artifact_set

if [[ -n "${REGEN_WORK_DIR:-}" ]]; then
  WORK_DIR=$REGEN_WORK_DIR
  mkdir -p "$WORK_DIR"
else
  WORK_DIR=$(mktemp -d)
  trap 'rm -rf "$WORK_DIR"' EXIT
fi

# Clone (or reuse) the Orchard source tree and force it to exactly the pinned PR commit.
# `git clean` keeps target/ so a reused REGEN_WORK_DIR stays warm.
prepare_orchard() {
  local dest="$WORK_DIR/orchard"
  # The checkout slot must be a directory the work dir owns: a symlink here would aim the
  # hard reset and clean below at whatever it points to.
  if [[ -L "$dest" ]]; then
    echo "VIOLATION: $dest is a symlink; the work dir must own its checkout" >&2
    exit 1
  fi
  if [[ ! -d "$dest/.git" ]]; then
    echo "Cloning orchard from $ORCHARD_URL"
    git clone --quiet "$ORCHARD_URL" "$dest"
  fi
  if ! git -C "$dest" cat-file -e "${ORCHARD_COMMIT}^{commit}" 2>/dev/null; then
    # Canonical GitHub exposes fork-backed pull requests through this repository-owned ref.
    git -C "$dest" fetch --quiet origin "refs/pull/$ORCHARD_PR/head"
  fi
  if ! git -C "$dest" cat-file -e "${ORCHARD_COMMIT}^{commit}" 2>/dev/null; then
    # The PR ref is movable: a force-push leaves the pinned SHA unreachable from it. GitHub serves
    # any pushed commit by full SHA, so fetch the pin itself before giving up.
    git -C "$dest" fetch --quiet origin "$ORCHARD_COMMIT" || true
  fi
  if ! git -C "$dest" cat-file -e "${ORCHARD_COMMIT}^{commit}" 2>/dev/null; then
    echo "VIOLATION: pinned orchard commit $ORCHARD_COMMIT is neither the head of zcash/orchard#$ORCHARD_PR nor fetchable by SHA from $ORCHARD_URL" >&2
    exit 1
  fi
  git -C "$dest" checkout --quiet --detach "$ORCHARD_COMMIT"
  git -C "$dest" reset --hard --quiet "$ORCHARD_COMMIT"
  git -C "$dest" clean -fdxq --exclude=target
  if [[ "$(git -C "$dest" rev-parse HEAD)" != "$ORCHARD_COMMIT" ]]; then
    echo "VIOLATION: orchard is not at pinned commit $ORCHARD_COMMIT" >&2
    exit 1
  fi
  if [[ -n "$(git -C "$dest" status --porcelain)" ]]; then
    echo "VIOLATION: orchard working tree is not clean at the pinned PR commit" >&2
    exit 1
  fi
  echo "orchard is at zcash/orchard#$ORCHARD_PR commit $ORCHARD_COMMIT."
}

prepare_orchard

# Orchard #544 pins its temporary halo2_proofs dependency through the canonical zcash/halo2 URL.
# Assert that its lockfile resolves exactly the #933 snapshot pinned above, so an upstream
# refresh of either side stops this script instead of silently capturing against different
# verifier sources.
orchard_dir="$WORK_DIR/orchard"
lock_entry=$(grep -A2 '^name = "halo2_proofs"$' "$orchard_dir/Cargo.lock")
expected_entry='name = "halo2_proofs"
version = "0.3.5"
source = "git+'"$HALO2_URL"'?rev='"$HALO2_COMMIT"'#'"$HALO2_COMMIT"'"'
if [[ "$lock_entry" != "$expected_entry" ]]; then
  echo "VIOLATION: Orchard lockfile does not resolve the pinned Halo2 commit:" >&2
  echo "$lock_entry" >&2
  exit 1
fi
echo "Cargo.lock resolves zcash/halo2#$HALO2_PR commit $HALO2_COMMIT through the canonical URL."

# Install orchard's pinned toolchain (mirrors fixtures.yml), then run every capture
# driver in one pass. The unanchored filter matches every upstream capture driver; each random
# driver runs its exact malformed-byte checks before exporting. It deliberately does not match the
# separate Rust-only `fingerprint_rejected_capture_two_actions` test. Orchard also ships a
# three-action match-only driver; it runs here but its output is not ingested, so only the four
# committed families below are diffed.
if command -v rustup >/dev/null 2>&1; then
  (cd "$WORK_DIR/orchard" && rustup show >/dev/null)
fi
mkdir -p "$WORK_DIR/out"
(
  cd "$WORK_DIR/orchard" &&
    env ORCHARD_LEAN_SINGLE_FIXTURE_OUT="$WORK_DIR/out/SingleAction.Honest.Fixture.lean" \
      ORCHARD_LEAN_MULTI_FIXTURE_OUT="$WORK_DIR/out/MultiAction.Honest.Fixture.lean" \
      ORCHARD_LEAN_SINGLE_RANDOM_FIXTURE_OUT="$WORK_DIR/out/SingleAction.Random.Fixture.lean" \
      ORCHARD_LEAN_MULTI_RANDOM_FIXTURE_OUT="$WORK_DIR/out/MultiAction.Random.Fixture.lean" \
      ORCHARD_LEAN_SINGLE_RANDOM_PROOF_OUT="$WORK_DIR/out/SingleAction.Random.proof-bytes.hex" \
      ORCHARD_LEAN_MULTI_RANDOM_PROOF_OUT="$WORK_DIR/out/MultiAction.Random.proof-bytes.hex" \
      cargo test --locked --lib --features verifier-fingerprint \
      circuit::fingerprint::fingerprint_capture -- --nocapture
)

status=0
stashed=0
for pair in "${pairs[@]}"; do
  generated="$WORK_DIR/out/${pair%%:*}"
  rest=${pair#*:}
  committed=${rest%%:*}
  requirement=${rest#*:}
  if [[ ! -f "$generated" ]]; then
    echo "VIOLATION: capture run did not produce $generated" >&2
    status=1
    continue
  fi
  if [[ -f "$committed" ]]; then
    if cmp -s "$generated" "$committed"; then
      echo "OK: $committed matches the regenerated capture byte-for-byte."
    else
      echo "VIOLATION: $committed differs from the regenerated capture ($generated)" >&2
      status=1
    fi
  elif [[ "$requirement" == "required" ]]; then
    echo "VIOLATION: committed fixture $committed is missing" >&2
    status=1
  else
    mkdir -p "$OUT_DIR"
    cp "$generated" "$OUT_DIR/${pair%%:*}"
    echo "Generated, no committed counterpart yet: $OUT_DIR/${pair%%:*}"
    stashed=$((stashed + 1))
  fi
done

if [[ $status -eq 0 ]]; then
  echo "fingerprint fixtures: all committed artifacts match; ${stashed} pending artifact(s) stashed in $OUT_DIR."
fi
exit $status
